### ISSUE TITLE
A Few Changes

### ISSUE THREAD

**Issue by Krisstoffer** [nikosdion/master-htaccess#3]
I have a few suggestions make of them what you will

www to non-www currently looks like this:

```
    if ($host = 'www.example.com' ) {
        rewrite ^/(.*)$ http://example.com/$1 permanent;
    }
```

Where as perhaps wiser to use:

```
server {
        server_name www.example.com;
        return 301 $scheme://example.com$request_uri;
}
```

I normally apply this above the standard server block and use $scheme as it accounts for http and https in one go. 

Lastly I would addition:
`client_max_body_size  10m;
`
Usually set this inline with the php.ini max file size it ensures uploads work as intended - more inline with larger files of course.

**Comment by nikosdion** [comment]
Regarding $host vs server_name, the intention was to let you easily expand it to other hostname redirections, not just non-www to www.

Regarding client_max_body_size I didn't want to touch it at all.
